# **IMPLEMENTASI PAK JUNTA**

Import Library

In [54]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import datasets
import matplotlib.pyplot as plt

Membaca data input

In [55]:
iris = datasets.load_iris()
features = iris['data']
target = iris['target']

Membuat objek model decision tree

In [57]:
decisiontree = DecisionTreeClassifier(random_state=0, max_depth=None,
                                      min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0,max_leaf_nodes=None,min_impurity_decrease=0)

Training model decision tree

In [58]:
model = decisiontree.fit(features, target)

Membuat prediksi

In [59]:
observation = [[5, 4, 3, 2]]
model.predict(observation)
model.predict_proba(observation)

array([[0., 1., 0.]])

Membuat grafik visualisasi

In [60]:
import pydotplus
from sklearn import tree
dot_data=tree.export_graphviz(decisiontree, out_file=None,
                                feature_names=iris['feature_names'],
                                class_names=iris['target_names'])
from IPython.display import Image
graph = pydotplus.graph_from_dot_data(dot_data)
Image(graph.create_png())
graph.write_png("iris.png")

True

# **IMPLEMENTASI PAK JUNTA DENGAN CSV FILE**

In [61]:
# import library
import numpy as np
import pandas as pd
from sklearn import tree
# load dataset
irisDataset = pd.read_csv('Dataset Iris.csv', delimiter=';', header=0)
# mengubah kolom Species ke unique int
irisDataset["Species"] = pd.factorize(irisDataset.Species)[0]
# menghapus kolom Id
irisDataset = irisDataset.drop(labels="Id", axis=1)
# mengubah dataset ke numpy(matrik)
irisDataset = irisDataset.to_numpy()

Split dataset

In [62]:
# membagi dataset 40 baris untuk train dan 20 untuk testing
dataTraining = np.concatenate((irisDataset[0:40, :], irisDataset[50:90, :]),
                              axis=0)
dataTesting = np.concatenate((irisDataset[40:50, :], irisDataset[90:100, :]),
                             axis=0)
# mempecah dataset ke input dan label
inputTraining = dataTraining[:, 0:4]
inputTesting = dataTesting[:, 0:4]
labelTraining = dataTraining[:, 4]
labelTesting = dataTesting[:, 4]

Deklarasi model decision tree dan training model

In [63]:
# deklarasi decision tree
model=tree.DecisionTreeClassifier()
# training model
model=model.fit(inputTraining, labelTraining)
# prediksi input data testing
hasilPrediksi=model.predict(inputTesting)
print("Label Sebenarnya : ", labelTesting)
print("Hasil Prediksi : ", hasilPrediksi)
# menghitung akurasi
prediksiBenar=(hasilPrediksi==labelTesting).sum()
prediksiSalah=(hasilPrediksi!=labelTesting).sum()
print("Prediksi Benar :", prediksiBenar, "data")
print("Prediksi Salah :", prediksiSalah, "data")
print("Akurasi :", prediksiBenar/(prediksiBenar+prediksiSalah)*100, "%")



Label Sebenarnya :  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Hasil Prediksi :  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Prediksi Benar : 20 data
Prediksi Salah : 0 data
Akurasi : 100.0 %


# **IMPLEMENTASI KASUS**

Import library

In [64]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import datasets
import matplotlib.pyplot as plt
import pandas as pd

Membaca Data input csv

In [65]:
# load dataset
bakery=pd.read_csv("bakery_customer_data.csv", delimiter=",", header=0)
# menampilkan isi dataset
bakery.head()

Bakery_ID  Customer_ID  Age      Gender  Items_Purchased  Amount_Spent  \
0  Bakery_1            1   22      Female                5          49.0   
1  Bakery_1            2   23      Female                4          39.0   
2  Bakery_1            3   64  Non-binary               16         137.0   
3  Bakery_1            4   32      Female                9          69.0   
4  Bakery_1            5   19      Female               16          95.0   

  Purchase_Date Time_of_Purchase Loyalty_Member Payment_Method  
0    2024-08-02        Afternoon            Yes      E-Payment  
1    2024-09-15          Morning             No      E-Payment  
2    2024-08-07          Morning             No           Cash  
3    2024-09-18          Morning            Yes           Cash  
4    2024-05-05          Evening             No           Cash

In [66]:
# mengubah kolom yang belum int yang akan dipake sebagai attribute
bakery["Payment_Method"] = pd.factorize(bakery.Payment_Method)[0]
bakery["Gender"] = pd.factorize(bakery.Gender)[0]
bakery["Loyalty_Member"] = pd.factorize(bakery.Loyalty_Member)[0]
bakery["Time_of_Purchase"] = pd.factorize(bakery.Time_of_Purchase)[0]
# menghapus kolom yg tidak dipakai
bakery=bakery.drop(labels="Bakery_ID", axis=1)
bakery=bakery.drop(labels="Customer_ID", axis=1)
bakery=bakery.drop(labels="Purchase_Date", axis=1)
# mengubah dataset ke numpy(matrik)
bakery = bakery.to_numpy()

In [70]:
print(bakery[:5])

[[ 22.   0.   5.  49.   0.   0.   0.]
 [ 23.   0.   4.  39.   1.   1.   0.]
 [ 64.   1.  16. 137.   1.   1.   1.]
 [ 32.   0.   9.  69.   1.   0.   1.]
 [ 19.   0.  16.  95.   2.   1.   1.]]


split dataset

In [75]:
# membagi dataset 40 baris untuk train dan 20 untuk testing
dataTraining = np.concatenate((bakery[0:60, :], bakery[60:120, :]),
                              axis=0)
dataTesting = np.concatenate((bakery[40:60, :], bakery[90:120, :]),
                             axis=0)
# mempecah dataset ke input dan label
inputTraining = dataTraining[:, 0:4]
inputTesting = dataTesting[:, 0:4]
labelTraining = dataTraining[:, 5]
labelTesting = dataTesting[:, 5]

Deklarasi model decision tree dan training model

In [76]:
# deklarasi decision tree
model=tree.DecisionTreeClassifier()
# training model
model=model.fit(inputTraining, labelTraining)
# prediksi input data testing
hasilPrediksi=model.predict(inputTesting)
print("Label Sebenarnya : ", labelTesting)
print("Hasil Prediksi : ", hasilPrediksi)
# menghitung akurasi
prediksiBenar=(hasilPrediksi==labelTesting).sum()
prediksiSalah=(hasilPrediksi!=labelTesting).sum()
print("Prediksi Benar :", prediksiBenar, "data")
print("Prediksi Salah :", prediksiSalah, "data")
print("Akurasi :", prediksiBenar/(prediksiBenar+prediksiSalah)*100, "%")



Label Sebenarnya :  [1. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
 1. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 1. 1. 1. 0.
 1. 1.]
Hasil Prediksi :  [1. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
 1. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 1. 1. 1. 0.
 1. 1.]
Prediksi Benar : 50 data
Prediksi Salah : 0 data
Akurasi : 100.0 %
